Python Day - 15 

Numpy Tricks

In [1]:
# np.sort 

import numpy  as np

a = np.random.randint(1,100,15)
a

array([97, 86, 24, 59, 35, 69, 33, 69, 27, 26, 96, 18, 62, 97,  1])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[61, 51, 34, 90],
       [77, 16,  2, 56],
       [34, 95, 92, 58],
       [97, 81, 45, 80],
       [39, 57, 72, 12],
       [20, 98, 18, 88]])

In [3]:
np.sort(a)

array([ 1, 18, 24, 26, 27, 33, 35, 59, 62, 69, 69, 86, 96, 97, 97])

In [4]:
np.sort(b,axis=0)

array([[20, 16,  2, 12],
       [34, 51, 18, 56],
       [39, 57, 34, 58],
       [61, 81, 45, 80],
       [77, 95, 72, 88],
       [97, 98, 92, 90]])

In [5]:
# np.append 
a
np.append(a,200)

array([ 97,  86,  24,  59,  35,  69,  33,  69,  27,  26,  96,  18,  62,
        97,   1, 200])

In [6]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[61.        , 51.        , 34.        , 90.        ,  0.92120431],
       [77.        , 16.        ,  2.        , 56.        ,  0.69704444],
       [34.        , 95.        , 92.        , 58.        ,  0.70040448],
       [97.        , 81.        , 45.        , 80.        ,  0.3614793 ],
       [39.        , 57.        , 72.        , 12.        ,  0.63448848],
       [20.        , 98.        , 18.        , 88.        ,  0.66760025]])

In [7]:
# np.concatend

c= np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [8]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [10]:
# np.unique

e= np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f= np.array([[1,2,3,1],[1,2,3,2]]) 

print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [11]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [12]:
# np.expand_dims

a

np.expand_dims(a,axis=0).shape

(1, 15)

In [13]:
np.expand_dims(a,axis=1)

array([[97],
       [86],
       [24],
       [59],
       [35],
       [69],
       [33],
       [69],
       [27],
       [26],
       [96],
       [18],
       [62],
       [97],
       [ 1]])

In [14]:
# np.where      
a

array([97, 86, 24, 59, 35, 69, 33, 69, 27, 26, 96, 18, 62, 97,  1])

In [15]:
np.where(a>50)

(array([ 0,  1,  3,  5,  7, 10, 12, 13], dtype=int64),)

In [16]:
np.where(a>50,0,a)

array([ 0,  0, 24,  0, 35,  0, 33,  0, 27, 26,  0, 18,  0,  0,  1])

In [17]:
a

array([97, 86, 24, 59, 35, 69, 33, 69, 27, 26, 96, 18, 62, 97,  1])

In [18]:
# np.argmax
np.argmax(a)

0

In [19]:
b

array([[61, 51, 34, 90],
       [77, 16,  2, 56],
       [34, 95, 92, 58],
       [97, 81, 45, 80],
       [39, 57, 72, 12],
       [20, 98, 18, 88]])

In [20]:
np.argmax(b,axis=1)

array([3, 0, 1, 0, 2, 1], dtype=int64)

In [21]:
# np.cumsum
a

array([97, 86, 24, 59, 35, 69, 33, 69, 27, 26, 96, 18, 62, 97,  1])

In [22]:
np.cumsum(a)

array([ 97, 183, 207, 266, 301, 370, 403, 472, 499, 525, 621, 639, 701,
       798, 799])

In [23]:
b

array([[61, 51, 34, 90],
       [77, 16,  2, 56],
       [34, 95, 92, 58],
       [97, 81, 45, 80],
       [39, 57, 72, 12],
       [20, 98, 18, 88]])

In [24]:
np.cumsum(b)

array([  61,  112,  146,  236,  313,  329,  331,  387,  421,  516,  608,
        666,  763,  844,  889,  969, 1008, 1065, 1137, 1149, 1169, 1267,
       1285, 1373])

In [25]:
# np.percentile
a

array([97, 86, 24, 59, 35, 69, 33, 69, 27, 26, 96, 18, 62, 97,  1])

In [26]:
np.percentile(a,100)

97.0

In [27]:
np.median(a)

59.0

In [28]:
# np.histogram
a

array([97, 86, 24, 59, 35, 69, 33, 69, 27, 26, 96, 18, 62, 97,  1])

In [29]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 3, 2, 0, 1, 3, 0, 1, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [30]:
# np.corrcoef

salary= np.array([2000,40000,50000,60000,700700]) 
exp = np.array([1,3,2,4,2])

np.corrcoef(salary,exp)

array([[ 1.        , -0.13507933],
       [-0.13507933,  1.        ]])

In [31]:
# np.isin
a
items=[10,20,30,40,50,60,70,80,90]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [32]:
# np.flip
a
np.flip(a)

array([ 1, 97, 62, 18, 96, 26, 27, 69, 33, 69, 35, 59, 24, 86, 97])

In [33]:
# np.put
np.put(a,[0,1],[110,530])

In [34]:
a

array([110, 530,  24,  59,  35,  69,  33,  69,  27,  26,  96,  18,  62,
        97,   1])

In [35]:
# np.delete
a
np.delete(a,0)

array([530,  24,  59,  35,  69,  33,  69,  27,  26,  96,  18,  62,  97,
         1])

Set Function

In [36]:
m=np.array([1,2,3,4,5,9])
n=np.array([1,2,3,4,5,6,7])

In [37]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [38]:
np.intersect1d(m,n)

array([1, 2, 3, 4, 5])

In [39]:
np.setdiff1d(m,n)

array([9])

In [40]:
np.setxor1d(m,n)

array([6, 7, 9])

In [41]:
np.in1d(m,1)

array([ True, False, False, False, False, False])

In [42]:
# np.clip
a

array([110, 530,  24,  59,  35,  69,  33,  69,  27,  26,  96,  18,  62,
        97,   1])

In [43]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 59, 35, 69, 33, 69, 27, 26, 75, 25, 62, 75, 25])