Python  Day - 13 

NUMPY FUNDAMENTALS

In [ ]:
import numpy as np 

# 1D array
a =np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array

c = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(c)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


numpy.ndarray

In [9]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [10]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# np.ones and np.zeros
np.ones((3,4))

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# np.random
np.random.random((3,4))

array([[0.58346381, 0.96582936, 0.55284483, 0.4574494 ],
       [0.58751894, 0.82108047, 0.6438865 , 0.20168563],
       [0.16467556, 0.46076742, 0.79463932, 0.62485078]])

In [19]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [17]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attribute

In [20]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [21]:
# ndim
a3.ndim

3

In [24]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
# size 
a3.size

8

In [27]:
# itemsize
a1.itemsize

4

In [28]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [32]:
# CHANGING DATATYPE

# astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

Array Operations

In [37]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operation 

# arithmetic(+ ,- ,* , %)
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [42]:
# relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
# vector operation
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])