Python  Day - 13 

NUMPY FUNDAMENTALS

In [1]:
import numpy as np 

# 1D array
a =np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D array

c = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(c)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# np.ones and np.zeros
np.ones((3,4))

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# np.random
np.random.random((3,4))

array([[0.92228107, 0.6237631 , 0.47299403, 0.46790126],
       [0.53167755, 0.55953389, 0.31881317, 0.40766879],
       [0.97724196, 0.89518793, 0.77319304, 0.63960997]])

In [9]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [10]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attribute

In [11]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [12]:
# ndim
a3.ndim

3

In [13]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# size 
a3.size

8

In [15]:
# itemsize
a1.itemsize

4

In [16]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [17]:
# CHANGING DATATYPE

# astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

Array Operations

In [18]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
# scalar operation 

# arithmetic(+ ,- ,* , %)
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [20]:
# relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
# vector operation
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array function

In [22]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[49., 27., 37.],
       [59., 47., 14.],
       [38., 25., 21.]])

In [ ]:
# max / min / sum / prod

# 0 --> col , 1 --> row
np.max(a1)

np.min(a1)

np.sum(a1)

np.prod(a1,axis=0)

array([109858.,  31725.,  10878.])

In [ ]:
# mean / medium / std / var

np.mean(a1)

np.median(a1)

37.0

In [34]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [35]:
# log and exponents

np.exp(a1)

array([[1.90734657e+21, 5.32048241e+11, 1.17191424e+16],
       [4.20121040e+25, 2.58131289e+20, 1.20260428e+06],
       [3.18559318e+16, 7.20048993e+10, 1.31881573e+09]])

In [36]:
# round / floor /cell

np.floor(np.random.random((2,3))*100)

array([[68., 50., 37.],
       [57., 27., 62.]])

Indexing & Slicing

In [41]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)

print(a2)

print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [42]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1[-1]

9

In [44]:
a1[0]

0

In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
a2[1,2]

6

In [47]:
a2[2,3]

11

In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
a3[1,0,1]

5

In [50]:
a3[0,0,0]

0

In [51]:
a3[1,1,0]

6

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[2:5]

array([2, 3, 4])

In [54]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2[0,:]

array([0, 1, 2, 3])

In [56]:
a2[:,2]

array([ 2,  6, 10])

In [58]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [60]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [61]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [72]:
a2[1,::3]

array([4, 7])

In [78]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [81]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [82]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [83]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[0,1]

array([3, 4, 5])

In [88]:
a3[1,:,1]

array([10, 13, 16])

In [94]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [95]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

iterating

In [106]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [107]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [108]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [109]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [111]:
# transpose

np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [112]:
# ravel

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [117]:
# horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [120]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [121]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [124]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [125]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]