Python Day - 15 

Numpy Tricks

In [ ]:
# np.sort 

import numpy  as np

a = np.random.randint(1,100,15)
a

array([18, 71, 87, 81, 14, 53, 36, 20, 74, 92,  7, 88, 99, 73,  6])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[53, 47, 37, 84],
       [61, 53, 20,  1],
       [19, 57, 44, 30],
       [21, 15, 81, 11],
       [24, 11, 97, 64],
       [95, 27, 84, 94]])

In [4]:
np.sort(a)

array([ 6,  7, 14, 18, 20, 36, 53, 71, 73, 74, 81, 87, 88, 92, 99])

In [6]:
np.sort(b,axis=0)

array([[19, 11, 20,  1],
       [21, 15, 37, 11],
       [24, 27, 44, 30],
       [53, 47, 81, 64],
       [61, 53, 84, 84],
       [95, 57, 97, 94]])

In [12]:
# np.append 
a
np.append(a,200)

array([ 18,  71,  87,  81,  14,  53,  36,  20,  74,  92,   7,  88,  99,
        73,   6, 200])

In [14]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[5.30000000e+01, 4.70000000e+01, 3.70000000e+01, 8.40000000e+01,
        5.84574486e-01],
       [6.10000000e+01, 5.30000000e+01, 2.00000000e+01, 1.00000000e+00,
        1.23235477e-01],
       [1.90000000e+01, 5.70000000e+01, 4.40000000e+01, 3.00000000e+01,
        4.90680715e-02],
       [2.10000000e+01, 1.50000000e+01, 8.10000000e+01, 1.10000000e+01,
        9.67646469e-01],
       [2.40000000e+01, 1.10000000e+01, 9.70000000e+01, 6.40000000e+01,
        4.16670788e-01],
       [9.50000000e+01, 2.70000000e+01, 8.40000000e+01, 9.40000000e+01,
        5.98629935e-01]])

In [15]:
# np.concatend

c= np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [19]:
# np.unique

e= np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f= np.array([[1,2,3,1],[1,2,3,2]]) 

print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [23]:
# np.expand_dims

a

np.expand_dims(a,axis=0).shape

(1, 15)

In [25]:
np.expand_dims(a,axis=1)

array([[18],
       [71],
       [87],
       [81],
       [14],
       [53],
       [36],
       [20],
       [74],
       [92],
       [ 7],
       [88],
       [99],
       [73],
       [ 6]])

In [ ]:
# np.where      
a

array([18, 71, 87, 81, 14, 53, 36, 20, 74, 92,  7, 88, 99, 73,  6])

In [27]:
np.where(a>50)

(array([ 1,  2,  3,  5,  8,  9, 11, 12, 13], dtype=int64),)

In [28]:
np.where(a>50,0,a)

array([18,  0,  0,  0, 14,  0, 36, 20,  0,  0,  7,  0,  0,  0,  6])

In [30]:
a

array([18, 71, 87, 81, 14, 53, 36, 20, 74, 92,  7, 88, 99, 73,  6])

In [33]:
# np.argmax
np.argmax(a)

12

In [31]:
b

array([[53, 47, 37, 84],
       [61, 53, 20,  1],
       [19, 57, 44, 30],
       [21, 15, 81, 11],
       [24, 11, 97, 64],
       [95, 27, 84, 94]])

In [32]:
np.argmax(b,axis=1)

array([3, 0, 1, 2, 2, 0], dtype=int64)

In [34]:
# np.cumsum
a

array([18, 71, 87, 81, 14, 53, 36, 20, 74, 92,  7, 88, 99, 73,  6])

In [35]:
np.cumsum(a)

array([ 18,  89, 176, 257, 271, 324, 360, 380, 454, 546, 553, 641, 740,
       813, 819])

In [36]:
b

array([[53, 47, 37, 84],
       [61, 53, 20,  1],
       [19, 57, 44, 30],
       [21, 15, 81, 11],
       [24, 11, 97, 64],
       [95, 27, 84, 94]])

In [37]:
np.cumsum(b)

array([  53,  100,  137,  221,  282,  335,  355,  356,  375,  432,  476,
        506,  527,  542,  623,  634,  658,  669,  766,  830,  925,  952,
       1036, 1130])

In [38]:
# np.percentile
a

array([18, 71, 87, 81, 14, 53, 36, 20, 74, 92,  7, 88, 99, 73,  6])

In [39]:
np.percentile(a,100)

99.0

In [40]:
np.median(a)

71.0

In [41]:
# np.histogram
a

array([18, 71, 87, 81, 14, 53, 36, 20, 74, 92,  7, 88, 99, 73,  6])

In [42]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 1, 0, 1, 0, 3, 3, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [43]:
# np.corrcoef

salary= np.array([2000,40000,50000,60000,700700]) 
exp = np.array([1,3,2,4,2])

np.corrcoef(salary,exp)

array([[ 1.        , -0.13507933],
       [-0.13507933,  1.        ]])

In [45]:
# np.isin
a
items=[10,20,30,40,50,60,70,80,90]
np.isin(a,items)

array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False])

In [47]:
# np.flip
a
np.flip(a)

array([ 6, 73, 99, 88,  7, 92, 74, 20, 36, 53, 14, 81, 87, 71, 18])

In [48]:
# np.put
np.put(a,[0,1],[110,530])

In [49]:
a

array([110, 530,  87,  81,  14,  53,  36,  20,  74,  92,   7,  88,  99,
        73,   6])

In [52]:
# np.delete
a
np.delete(a,0)

array([530,  87,  81,  14,  53,  36,  20,  74,  92,   7,  88,  99,  73,
         6])

Set Function

In [54]:
m=np.array([1,2,3,4,5,9])
n=np.array([1,2,3,4,5,6,7])

In [55]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [56]:
np.intersect1d(m,n)

array([1, 2, 3, 4, 5])

In [57]:
np.setdiff1d(m,n)

array([9])

In [58]:
np.setxor1d(m,n)

array([6, 7, 9])

In [59]:
np.in1d(m,1)

array([ True, False, False, False, False, False])

In [60]:
# np.clip
a

array([110, 530,  87,  81,  14,  53,  36,  20,  74,  92,   7,  88,  99,
        73,   6])

In [62]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 53, 36, 25, 74, 75, 25, 75, 75, 73, 25])